# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            UniquelyTwo
tagline:          'Home of Jupyter notebooks'
description:      'Find interesting and helpful notebooks.'
url:              http://uniquelyTwo.github.io
baseurl:          /

author:
  name:           'Uniquely Two'
  url:            mailto:uniquelyTwo@gmail.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/uniquelyTwo/uniquelyTwo.github.io
